### PR TITLE
Modal: fix scroll issue

### LINKED ISSUE #602: Modals are not scrollable in the projects
For iOS devices the modals are not scrollable.
Bug report: https://glints.slack.com/archives/CBM88R7U1/p1613014751124600

### PR DESCRIPTION
**Pull request by rosslo**
The first commit is to fix this issue https://github.com/glints-dev/glints-aries/issues/602
And the second commit is to fix the footer UI below when the `centering` prop is `true`.

Screen Shot 2021-02-17 at 5 31 12 PM

### CODE REVIEW

File: src/Display/Modal/ModalStyle.ts [hunk 1]
```diff
@@ -81,8 +81,9 @@ export const ModalContentArea = styled.div<InnerProps>`
   ${({ centering }) => {
     if (centering) {
       return `
+        display: flex;
+        flex-direction: column;
         max-height: 85vh;
-        overflow: auto;
```
Comment (rosslo) [inline src/Display/Modal/ModalStyle.ts:85]: When the `centering` is `true`, only the modal body could be scrollable.

**Review by ritikamotwani — APPROVED** [review]
LGTM! Thanks!
