### PR TITLE
Fix dropdown onclick

### LINKED ISSUE #348: Clicking a Dropdown Item Sets its Label to the Item's Value
See https://github.com/glints-dev/glints-aries/pull/347

The label should be set to the Item's `innerHTML`, not the `value`.

### PR DESCRIPTION
**Pull request by westwood846**
Fixes #348 

This change is safe to make because the `handleKeyDown` function already sets the label to the option's label.

### CODE REVIEW

File: src/Navigation/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -71,8 +71,7 @@ const Dropdown = (props: Props) => {
     const itemElement = e.target as HTMLLIElement;
 
     if (itemElement.dataset.value) {
-      // TODO: This should probably set to itemElement.innerHTML
-      setDropdownLabel(itemElement.dataset.value);
+      setDropdownLabel(itemElement.innerHTML);
```
Comment (tingtingdisco) [inline src/Navigation/Dropdown/Dropdown.tsx:74]: shall we move `setDropdownLabel(itemElement.innerHTML)` out of this `if` block? I think the dropdown label should always be updated whether `itemElement.dataset.value` has value or not. What do you think?

**Review by tingtingdisco — APPROVED** [review]
LGTM

File: src/Navigation/Dropdown/Dropdown.tsx (hunk 1 above)
Comment (westwood846) [reply src/Navigation/Dropdown/Dropdown.tsx:74]: Oh actually I think this would break some usages of this component because people have been using it as a dropdown menu where clicking an option will trigger an action without changing the label. Those don't set the value to achieve the effect.
