### PR TITLE
Select: Fix mismatch

### LINKED ISSUE #210: Select: Fix UI Mismatches
GDS: https://share.goabstract.com/9f42c17f-10b8-444d-bc85-e9435d482d21?sha=
https://docs.google.com/document/d/1pHImZ2YXcG0WxMU5ll1y9zBygyErR2EjR8xu3Y2lgDw/edit

### PR DESCRIPTION
**Pull request by tingtingdisco**
Closes #210 

fixed these:
https://docs.google.com/document/d/1pHImZ2YXcG0WxMU5ll1y9zBygyErR2EjR8xu3Y2lgDw/edit

updated storybook
Screen Shot 2020-04-23 at 7 01 50 PM

### CODE REVIEW

File: stories/Input/SelectStory.tsx [hunk 1]
```diff
@@ -38,17 +38,15 @@ const props = {
       defaultValue: '',
       possibleValue: 'any',
       require: 'no',
-      description:
-        'Sets error state on component. If string, the error will be shown below the select',
+      description: `WARNING: Will only allow string type in the future, don't customize error message style. Sets error state on component. If string, the error will be shown below the select`,
     },
     {
       name: 'renderError',
```
Comment (rosslo) [inline stories/Input/SelectStory.tsx:44]: Seems to neither `employers` nor `dst` use `renderError`. Do you think we can just remove it in this PR?

File: src/Input/Select/Select.tsx [hunk 2]
```diff
@@ -239,7 +239,11 @@ const Select: ISelect = (props: Props) => {
       className={classNames('aries-select', className)}
       ref={node}
     >
-      <SelectWrapper className="select-inputwrapper" isFocus={isFocus}>
+      <SelectWrapper
+        className="select-inputwrapper"
+        isFocus={isFocus}
+        small={small}
```
Comment (rosslo) [inline src/Input/Select/Select.tsx:245]: Do you think using `size` to accept string ('small' | 'large') will be more scalable?

**Comment by rosslo** [comment]
Should the color of text change when select is hovered?
image

File: stories/Input/SelectStory.tsx [hunk 3]
```diff
@@ -138,8 +136,14 @@ const props = {
 
 const Story = (
   <div>
+    <div style={{ marginBottom: '1rem' }}>2 sizes only</div>
```
Comment (rosslo) [inline stories/Input/SelectStory.tsx:139]: I think `2 types only` will be more suitable for this section 🤔

Comment (tingtingdisco) [reply stories/Input/SelectStory.tsx:139]: but it's sizes

**Comment by tingtingdisco** [comment]
> Should the color of text change when select is hovered?
> image

I will ask Precious

File: stories/Input/SelectStory.tsx (hunk 3 above)
Comment (rosslo) [reply stories/Input/SelectStory.tsx:139]: Can have another section called `sizes`?

Comment (rosslo) [reply stories/Input/SelectStory.tsx:139]: Would you mind to check the button story on the branch `feature/GDS-button`?

I'm trying to introduce Button by props rather than types (current).

File: stories/Input/SelectStory.tsx (hunk 1 above)
Comment (tingtingdisco) [reply stories/Input/SelectStory.tsx:44]: no, I am only fix UI mismatching

File: src/Input/Select/Select.tsx (hunk 2 above)
Comment (tingtingdisco) [reply src/Input/Select/Select.tsx:245]: I am only fix UI mismatching, don't want to change the interface in the same PR.

File: stories/Input/SelectStory.tsx (hunk 3 above)
Comment (tingtingdisco) [reply stories/Input/SelectStory.tsx:139]: prefer do these things separately.

**Comment by rosslo** [comment]
@tingtingdisco LGTM

**Review by rosslo — APPROVED** [review]
