### PR TITLE
Feature/fix button mismatch

### LINKED ISSUE #193: Button: Fix UI Mismatches
GDS: https://share.goabstract.com/53712b69-e5ac-407d-9d15-3484a04fb285?sha=

### LINKED ISSUE #265: Button: Using `tag='a'` on PrimaryButton causes the text to change to the native `a` color
Expected outcome: Color should still default to black for all states (active, hover, visited)

image

Code:
```
<Button variant="primary" theme="yellow" tag="a">
    <MailSolidIcon /> Sign up with email
</Button>
```

### PR DESCRIPTION
**Pull request by rosslo**
Related Issues: 
- https://github.com/glints-dev/glints-aries/issues/193
- https://github.com/glints-dev/glints-aries/issues/265

What changed:
- Fix the text color of the `Primary Button` with `a` tag
- Fix the `font-size` of the button with `small` prop
- Change the text color of `Default White Button` to blue
- Add warning message for deprecated`Secondary Button` and some `theme` values
- Add `startIcon` and `endIcon` props because the margin between icon and text is defined in GDS.
- Revamp the button story to be categorized by props instead of types

### CODE REVIEW

File: stories/General/ButtonStory.tsx [hunk 1]
```diff
@@ -1,267 +1,388 @@
...
+  };
+  return (
+    <StorybookComponent
+      title="Button"
+      code="import { Button } from 'glints-aries'"
+      usage={usage}
+      propsObject={propsObject}
+    >
+      <Heading>Variants</Heading>
+      <h3></h3>
```
Comment (westwood846) [inline stories/General/ButtonStory.tsx]:
```suggestion
```

File: stories/General/ButtonStory.tsx [hunk 2]
```diff
@@ -1,267 +1,388 @@
...
+        possibleValue: <code>true | false</code>,
+        require: 'no',
+        description: 'Sets Button to disable state.',
+      },
+    ],
+  };
+  return (
+    <StorybookComponent usage={usage} propsObject={propsObject}>
+      <Heading>Disabled</Heading>
+      <h3></h3>
```
Comment (westwood846) [inline stories/General/ButtonStory.tsx]:
```suggestion
```

File: stories/General/ButtonStory.tsx [hunk 3]
```diff
@@ -1,267 +1,388 @@
...
+        possibleValue: <code>true | false</code>,
+        require: 'no',
+        description: "Removes Button's effect when hovered",
+      },
+    ],
+  };
+  return (
+    <StorybookComponent usage={usage} propsObject={propsObject}>
+      <Heading>Button without hovered background</Heading>
+      <h3></h3>
```
Comment (westwood846) [inline stories/General/ButtonStory.tsx]:
```suggestion
```

**Review by westwood846 — CHANGES_REQUESTED** [review]
You have some empty `<h3>`s in a couple places, might be a copy-paste error. Also note the autogenerated warning.

**Review by westwood846 — APPROVED** [review]
LGTM!
