### PR TITLE
Tab: Fix the enum issue and make children optional

### LINKED ISSUE #401: Tab: make children prop optional & fix enum issues
image

### PR DESCRIPTION
**Pull request by ritikamotwani**
Fixes: #401

### CODE REVIEW

File: src/Display/Tabs/Tabs.tsx [hunk 1]
```diff
@@ -112,12 +109,12 @@ Tabs.Pane = TabPane;
 
 interface Props {
   children: React.ReactNode;
-  variant?: EHorizontalTabVariant;
+  variant?: string;
```
Comment (rosslo) [inline src/Display/Tabs/Tabs.tsx]: @ritikamotwani could you help experiment the following?
```
type Variants = keyof typeof EHorizontalTabVariant;
variant?: Variants;
```
I was thinking if we can have `variant? 'underlined' | 'colored'`. It might help us throw the error when we pass a wrong `variant` value in other projects.

Comment (ritikamotwani) [reply src/Display/Tabs/Tabs.tsx]: Oh I think `variant? 'underlined' | 'colored'` would be better

Comment (ritikamotwani) [reply src/Display/Tabs/Tabs.tsx]: Updated with `variant?: 'underlined' | 'colored'`
It would throw an error, if the value is incorrect for variant, theme, alignment

Comment (rosslo) [reply src/Display/Tabs/Tabs.tsx]: I thought `type Variants = keyof typeof EHorizontalTabVariant;` equals `'underlined' | 'colored'`. So we can just need to update one place (enum) when we have a new value.

Btw, I think we can still have `type Variant = ''underlined' | 'colored'` and `variants? Variant` instead of setting `varaints? 'underlined' | 'colored'` everywhere.

Comment (ritikamotwani) [reply src/Display/Tabs/Tabs.tsx]: The reason I didn't use this is, when I write this it becomes `"UNDERLINED" | "COLORED"`, and then if I try using `typeof ETabAlignment[keyof typeof ETabAlignment]` it's the same as ETabVariant type (https://stackoverflow.com/questions/53662208/types-from-both-keys-and-values-of-object-in-typescript)

Comment (rosslo) [reply src/Display/Tabs/Tabs.tsx]: Ohhh right, it is `keyof` 😅 , then what do you think of using `type Variant = ''underlined' | 'colored'`?

Comment (ritikamotwani) [reply src/Display/Tabs/Tabs.tsx]: Yes, that's much better! Thanks

**Review by rosslo — APPROVED** [review]
